export const projects = [
  { title: "Amazon Rufus", description: "My first experience helping take GenAI beyond a prototype and into production-oriented engineering — with a careful focus on customer experience.", themes: "GenAI · RAG · AWS · Customer experience", art: "context and retrieval", link: null },
  { title: "CrimeMap Atlanta", description: "An interactive way to make neighborhood crime data legible: people can weigh what matters to them and see a more personal view of place.", themes: "React · Next.js · deck.gl · Data visualization", art: "city signals", link: "https://github.com/Maulishri" },
  { title: "RAG Assistant", description: "A practical enterprise AI pattern for getting the right knowledge to the right person, with retrieval as a first-class part of the experience.", themes: "LLMs · Retrieval · Architecture · Evaluation", art: "question and answer", link: "https://github.com/Maulishri" },
];
export const timeline = [
  { id: "amazon-checkout", date: "Jun 2025—now", sortOrder: 202506, title: "Amazon Checkout", role: "Software Development Engineer", description: "Building customer-facing systems where reliability, clarity, and latency matter — because the invisible parts of a product are often the ones users feel most.", tags: ["Distributed systems", "Reliability", "Latency", "AWS"] },
  { id: "georgia-tech", date: "Aug2023—May 2025", sortOrder: 202503, title: "Graduated from Georgia Tech", role: "MS Computer Science", description: "Graduate school expanded my lens: machine learning, visualization, HCI, and teaching all offered different ways to understand the person behind a system.", tags: ["ML", "Visualization", "HCI", "Computer vision"] },
  { id: "williamson", date: "Apr 2025", sortOrder: 202504, title: "Marshall D. Williamson Fellowship", role: "Georgia Institute of Technology", description: "Recognized by Georgia Tech as a well-rounded second-year master’s student demonstrating academic excellence and leadership.", tags: ["Leadership", "Academic excellence"], sideQuest: true },
  { id: "georgia-tech-ta-2", date: "Aug-Dec 2024", sortOrder: 202503, title: "Georgia Tech", role: "Teaching Assistant · Data Analytics, Visualization & HCI", description: "Explored how to make complex data more legible and actionable, and how to design interfaces that help people understand and decide with confidence.", tags: ["Visualization", "HCI", "Data legibility"] },
  { id: "rufus", date: "May—Aug 2024", sortOrder: 202405, title: "Amazon Rufus", role: "Software Engineering · GenAI / RAG", description: "My first experience taking GenAI beyond a prototype and into production-oriented engineering, where quality and customer trust both matter.", tags: ["GenAI", "RAG", "AWS", "Customer experience"] },
  { id: "jackson", date: "Apr 2024", sortOrder: 202404, title: "Donald V. Jackson Fellowship", role: "Georgia Institute of Technology", description: "Recognized by Georgia Tech for all-round excellence across leadership and academics.", tags: ["Leadership", "Academics"], sideQuest: true },
  { id: "georgia-tech-ta-1", date: "Jan-May 2024", sortOrder: 202303, title: "Georgia Tech", role: "Teaching Assistant · Human Machine Learning", description: "Explored the intersection of human psychology and machine learning, focusing on how to design systems that augment human thinking and capabilities.", tags: ["Human psychology", "Machine learning", "HCI"] },
  { id: "georgia-tech-admit", date: "2023", sortOrder: 202203, title: "Georgia Tech", role: "Student", description: "Started my journey in the MS Computer Science program at Georgia Tech. My cousework was focused on the intersection of Computer Science, Human Computer Interaction, Machine Learning and Data Analytics.", tags: ["Machine Learning", "Data Analytics", "HCI"] },
  { id: "jpmorgan", date: "2022—23", sortOrder: 202201, title: "JPMorgan Chase", role: "Software Engineer · Asset and Wealth Management · Global Risk Technology", description: "Built software and analytics for global wealth management, learning how resilient data systems make better decisions possible at scale.", tags: ["Java", "GraphQL", "Python", "AWS"] },
  { id: "vit", date: "2018—22", sortOrder: 201808, title: "Vellore Institute of Technology", role: "ECE · IoT & sensors", description: "I started with sensors, embedded systems, and the satisfying feeling of making something respond to the physical world.", tags: ["IoT", "Embedded systems", "Curiosity"] },
  { id: "ghc", date: "2021", sortOrder: 202107, title: "Grace Hopper Scholar", role: "AnitaB.org", description: "A formative opportunity to join a global community of women in computing and see a larger future for myself in technology.", tags: ["Community", "Women in computing"], sideQuest: true },
  { id: "techgig", date: "2020", sortOrder: 202001, title: "TechGig Geek Goddess Semi-Finalist", role: "Top 0.98% globally", description: "An early reminder that curiosity and consistent practice can open doors beyond the classroom.", tags: ["Problem solving", "Early career"], sideQuest: true },
  { id: "kpmg", date: "2019", sortOrder: 201900, title: "KPMG", role: "Data Engineer Intern", description: "An early view of how technology can support complex organizations, and why translating needs into useful systems is its own craft.", tags: ["Collaboration", "Product context", "Communication"] },
  { id: "creative", date: "Always", sortOrder: 201800, title: "Making room to make", role: "Painting · soccer · dance · running", description: "The things that don’t fit neatly into a job title still matter. They keep me observant, collaborative, and interested in the world outside the terminal.", tags: ["Painting", "Soccer", "Dance", "Books"], sideQuest: true }
];
export const contact = { email: "maulishribhandari@gmail.com", linkedIn: "https://www.linkedin.com/in/maulishri-bhandari-41b172190/", github: "https://github.com/Maulishri" };
